<?php

namespace ContainerSQjrkC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OizoAakService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OizoAak' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OizoAak'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\ApiController::post' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Api\\ApiController::register' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\DashboardController::profile' => ['privates', '.service_locator.6VkLT8t', 'get_ServiceLocator_6VkLT8tService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\PostController::delete' => ['privates', '.service_locator.Sq6qDTV', 'get_ServiceLocator_Sq6qDTVService', true],
            'App\\Controller\\PostController::edit' => ['privates', '.service_locator.Sq6qDTV', 'get_ServiceLocator_Sq6qDTVService', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\PostController::new' => ['privates', '.service_locator.m.lF_QO', 'get_ServiceLocator_M_LFQOService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.ckGzNSR', 'get_ServiceLocator_CkGzNSRService', true],
            'App\\Controller\\PostController::test' => ['privates', '.service_locator.rQUuUyH', 'get_ServiceLocator_RQUuUyHService', true],
            'App\\Controller\\PostController::toggleFollow' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\PostController::user' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Api\\ApiController:post' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Api\\ApiController:register' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\DashboardController:profile' => ['privates', '.service_locator.6VkLT8t', 'get_ServiceLocator_6VkLT8tService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\PostController:delete' => ['privates', '.service_locator.Sq6qDTV', 'get_ServiceLocator_Sq6qDTVService', true],
            'App\\Controller\\PostController:edit' => ['privates', '.service_locator.Sq6qDTV', 'get_ServiceLocator_Sq6qDTVService', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\PostController:new' => ['privates', '.service_locator.m.lF_QO', 'get_ServiceLocator_M_LFQOService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.ckGzNSR', 'get_ServiceLocator_CkGzNSRService', true],
            'App\\Controller\\PostController:test' => ['privates', '.service_locator.rQUuUyH', 'get_ServiceLocator_RQUuUyHService', true],
            'App\\Controller\\PostController:toggleFollow' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\PostController:user' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Api\\ApiController::post' => '?',
            'App\\Controller\\Api\\ApiController::register' => '?',
            'App\\Controller\\DashboardController::profile' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\PostController::delete' => '?',
            'App\\Controller\\PostController::edit' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::new' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Controller\\PostController::test' => '?',
            'App\\Controller\\PostController::toggleFollow' => '?',
            'App\\Controller\\PostController::user' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Api\\ApiController:post' => '?',
            'App\\Controller\\Api\\ApiController:register' => '?',
            'App\\Controller\\DashboardController:profile' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\PostController:delete' => '?',
            'App\\Controller\\PostController:edit' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:new' => '?',
            'App\\Controller\\PostController:show' => '?',
            'App\\Controller\\PostController:test' => '?',
            'App\\Controller\\PostController:toggleFollow' => '?',
            'App\\Controller\\PostController:user' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
