<?php

namespace ContainerSQjrkC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewPostListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\NewPostListener' shared autowired service.
     *
     * @return \App\EventListener\NewPostListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'NewPostListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\EventListener\\NewPostListener'])) {
            return $container->privates['App\\EventListener\\NewPostListener'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['App\\EventListener\\NewPostListener'])) {
            return $container->privates['App\\EventListener\\NewPostListener'];
        }

        return $container->privates['App\\EventListener\\NewPostListener'] = new \App\EventListener\NewPostListener(new \Symfony\Component\Mailer\Mailer($a, ($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService()), $b));
    }
}
