<?php

namespace ContainerSQjrkC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPusherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pusher\Pusher' shared autowired service.
     *
     * @return \Pusher\Pusher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pusher'.\DIRECTORY_SEPARATOR.'pusher-php-server'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PusherInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pusher'.\DIRECTORY_SEPARATOR.'pusher-php-server'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Pusher.php';

        $container->privates['Pusher\\Pusher'] = $instance = new \Pusher\Pusher($container->getEnv('PUSHER_KEY'), $container->getEnv('PUSHER_SECRET'), $container->getEnv('PUSHER_APP_ID'), ['cluster' => $container->getEnv('PUSHER_CLUSTER'), 'useTLS' => true]);

        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        return $instance;
    }
}
