<?php

namespace ContainerSQjrkC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\SearchComponent' autowired service.
     *
     * @return \App\Twig\Components\SearchComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'SearchComponent.php';

        $container->factories['App\\Twig\\Components\\SearchComponent'] = function () use ($container) {
            $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

            if (isset($container->services['App\\Twig\\Components\\SearchComponent'])) {
                return $container->services['App\\Twig\\Components\\SearchComponent'];
            }

            return new \App\Twig\Components\SearchComponent($a);
        };

        return $container->factories['App\\Twig\\Components\\SearchComponent']();
    }
}
