<?php

namespace ContainerSQjrkC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestCalculatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Services\TestCalculator' shared autowired service.
     *
     * @return \App\Services\TestCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'TestCalculator.php';

        return $container->services['App\\Services\\TestCalculator'] = new \App\Services\TestCalculator();
    }
}
