<?php

namespace ContainerSQjrkC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ComponentFactory.php';

        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        return $container->privates['ux.twig_component.component_factory'] = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'like' => [false, 'App\\Twig\\Components\\LikeComponent', 'getLikeComponentService', true],
            'like_icon' => [false, 'App\\Twig\\Components\\LikeIconComponent', 'getLikeIconComponentService', true],
            'search' => [false, 'App\\Twig\\Components\\SearchComponent', 'getSearchComponentService', true],
            'unlike_icon' => [false, 'App\\Twig\\Components\\UnlikeIconComponent', 'getUnlikeIconComponentService', true],
        ], [
            'like' => 'App\\Twig\\Components\\LikeComponent',
            'like_icon' => 'App\\Twig\\Components\\LikeIconComponent',
            'search' => 'App\\Twig\\Components\\SearchComponent',
            'unlike_icon' => 'App\\Twig\\Components\\UnlikeIconComponent',
        ]), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), $a, ['like' => ['key' => 'like', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'route' => 'ux_live_component', 'service_id' => 'App\\Twig\\Components\\LikeComponent', 'class' => 'App\\Twig\\Components\\LikeComponent', 'template' => 'components/like.html.twig'], 'like_icon' => ['key' => 'like_icon', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'service_id' => 'App\\Twig\\Components\\LikeIconComponent', 'class' => 'App\\Twig\\Components\\LikeIconComponent', 'template' => 'components/like_icon.html.twig'], 'search' => ['key' => 'search', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'route' => 'ux_live_component', 'service_id' => 'App\\Twig\\Components\\SearchComponent', 'class' => 'App\\Twig\\Components\\SearchComponent', 'template' => 'components/search.html.twig'], 'unlike_icon' => ['key' => 'unlike_icon', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'service_id' => 'App\\Twig\\Components\\UnlikeIconComponent', 'class' => 'App\\Twig\\Components\\UnlikeIconComponent', 'template' => 'components/unlike_icon.html.twig']]);
    }
}
