<?php

namespace Container5xfXB24;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ImageUploader' shared autowired service.
     *
     * @return \App\Services\ImageUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'ImageUploader.php';

        return $container->privates['App\\Services\\ImageUploader'] = new \App\Services\ImageUploader((\dirname(__DIR__, 4).'/public/images'));
    }
}
