<?php

namespace Container5xfXB24;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeIconComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\LikeIconComponent' autowired service.
     *
     * @return \App\Twig\Components\LikeIconComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'LikeIconComponent.php';

        $container->factories['service_container']['App\\Twig\\Components\\LikeIconComponent'] = function () use ($container) {
            return new \App\Twig\Components\LikeIconComponent();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\LikeIconComponent']();
    }
}
