<?php

namespace Container5xfXB24;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\LikeComponent' autowired service.
     *
     * @return \App\Twig\Components\LikeComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'LikeComponent.php';

        $container->factories['App\\Twig\\Components\\LikeComponent'] = function () use ($container) {
            $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

            if (isset($container->services['App\\Twig\\Components\\LikeComponent'])) {
                return $container->services['App\\Twig\\Components\\LikeComponent'];
            }

            return new \App\Twig\Components\LikeComponent($a, ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
        };

        return $container->factories['App\\Twig\\Components\\LikeComponent']();
    }
}
