<?php

namespace Container5xfXB24;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnlikeIconComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\UnlikeIconComponent' autowired service.
     *
     * @return \App\Twig\Components\UnlikeIconComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'UnlikeIconComponent.php';

        $container->factories['service_container']['App\\Twig\\Components\\UnlikeIconComponent'] = function () use ($container) {
            return new \App\Twig\Components\UnlikeIconComponent();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\UnlikeIconComponent']();
    }
}
