<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xfXB24\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xfXB24/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xfXB24.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xfXB24\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xfXB24\App_KernelDevDebugContainer([
    'container.build_hash' => '5xfXB24',
    'container.build_id' => '4677738e',
    'container.build_time' => 1768138799,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xfXB24');
